version: '3'
services:
  tele:
    image: ${CI_REGISTRY_IMAGE}/tele:${DOCKER_IMG_TAG}
    build:
      context: ./
      dockerfile: Dockerfile
    expose:
      - ${PORT}
    environment:
      - PORT=${PORT}
    env_file:
      - .env
    networks:
      - caddy
    labels:
      caddy: ${HOST_DOMAIN}
      caddy.reverse_proxy: '{{upstreams ${PORT}}}'

networks:
  caddy:
    external: true
